---
swagger: "2.0"
info:
  description: "Questo servizio ritorna la data e l'ora attuali in UTC.\n\n#### Documentazione\n\
    Il servizio Ora esatta ritorna l'ora del server in formato RFC5424 (syslog).\n\
    \n`2018-12-30T12:23:32Z`\n\n##### Sottosezioni\nE' possibile utilizzare - con\
    \ criterio - delle sottosezioni.\n\n#### Note\n\nIl servizio non richiede autenticazione,\
    \ ma va' usato rispettando gli\nheader di throttling esposti in conformita' alle\
    \ Linee Guida del Modello di interoperabilita'.\n\n#### Informazioni tecniche\
    \ ed esempi\n\nEsempio:\n\n```\nhttp http://localhost:8443/datetime/v1/echo\n\
    {\n  'datetime': '2018-12-30T12:23:32Z'\n}\n```\n"
  version: "1.0.0"
  title: "Ora esatta."
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Roberto Polli"
    url: "https://twitter.com/ioggstream"
    email: "robipolli@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-api-id: "00000000-0000-0000-0000-000000000000"
  x-audience:
  - "public"
host: "api.example.com"
basePath: "/datetime/v1"
tags:
- name: "public"
  description: "Retrieve informations"
  externalDocs:
    url: "http://docs.my-api.com/pet-operations.htm"
schemes:
- "https"
paths:
  /echo:
    get:
      tags:
      - "public"
      summary: "Ritorna un timestamp in formato RFC5424."
      description: "Ritorna un timestamp in formato RFC5424\nprendendola dal server\
        \ attuale.\n"
      operationId: "get_echo"
      produces:
      - "application/problem+json"
      parameters: []
      responses:
        200:
          description: "Il server ha ritornato il timestamp.\n"
          schema:
            $ref: "#/definitions/Timestampa"
          headers:
            Retry-After:
              type: "integer"
              format: "int32"
              description: "Retry contacting the endpoint *at least* after seconds.\n\
                See https://tools.ietf.org/html/rfc7231#section-7.1.3"
            X-RateLimit-Limit:
              type: "integer"
              format: "int32"
              description: "The number of allowed requests in the current period"
            X-RateLimit-Remaining:
              type: "integer"
              format: "int32"
              description: "The number of remaining requests in the current period"
            X-RateLimit-Reset:
              type: "integer"
              format: "int32"
              description: "The number of seconds left in the current period"
        429:
          description: "Too many requests"
          schema:
            $ref: "#/definitions/Problem"
          headers:
            Retry-After:
              type: "integer"
              format: "int32"
              description: "Retry contacting the endpoint *at least* after seconds.\n\
                See https://tools.ietf.org/html/rfc7231#section-7.1.3"
            X-RateLimit-Limit:
              type: "integer"
              format: "int32"
              description: "The number of allowed requests in the current period"
            X-RateLimit-Remaining:
              type: "integer"
              format: "int32"
              description: "The number of remaining requests in the current period"
            X-RateLimit-Reset:
              type: "integer"
              format: "int32"
              description: "The number of seconds left in the current period"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/Problem"
          headers:
            Retry-After:
              type: "integer"
              format: "int32"
              description: "Retry contacting the endpoint *at least* after seconds.\n\
                See https://tools.ietf.org/html/rfc7231#section-7.1.3"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Problem"
      x-swagger-router-controller: "swagger_server.controllers.public_controller"
definitions:
  Problem:
    type: "object"
    properties:
      detail:
        type: "string"
        example: "Connection to database timed out"
        description: "A human readable explanation specific to this occurrence of\
          \ the\nproblem.\n"
      instance:
        type: "string"
        format: "uri"
        description: "An absolute URI that identifies the specific occurrence of the\
          \ problem.\nIt may or may not yield further information if dereferenced.\n"
      status:
        type: "integer"
        format: "int32"
        example: 503
        description: "The HTTP status code generated by the origin server for this\
          \ occurrence\nof the problem.\n"
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
      title:
        type: "string"
        description: "A short, summary of the problem type. Written in english and\
          \ readable\nfor engineers (usually not suited for non technical stakeholders\
          \ and\nnot localized); example: Service Unavailable\n"
      type:
        type: "string"
        format: "uri"
        example: "https://tools.ietf.org/html/rfc7231#section-6.6.4"
        description: "An absolute URI that identifies the problem type.  When dereferenced,\n\
          it SHOULD provide human-readable documentation for the problem type\n(e.g.,\
          \ using HTML).\n"
        default: "about:blank"
  Timestampa:
    type: "object"
    properties:
      timestamp:
        type: "string"
        format: "date-time"
        example: "2018-12-30T12:23:32Z"
    description: "Un Timestamp in RFC5424"
x-components:
  responses:
    404NotFound:
      content:
        application/problem+json:
          schema:
            $ref: "#/definitions/Problem"
      description: "Not Found"
    429TooManyRequests:
      description: "Too many requests"
      headers:
        Retry-After:
          description: "Retry contacting the endpoint *at least* after seconds.\n\
            See https://tools.ietf.org/html/rfc7231#section-7.1.3"
          format: "int32"
          type: "integer"
        X-RateLimit-Limit:
          description: "The number of allowed requests in the current period"
          format: "int32"
          type: "integer"
        X-RateLimit-Remaining:
          description: "The number of remaining requests in the current period"
          format: "int32"
          type: "integer"
        X-RateLimit-Reset:
          description: "The number of seconds left in the current period"
          format: "int32"
          type: "integer"
      schema:
        $ref: "#/definitions/Problem"
    503ServiceUnavailable:
      description: "Service Unavailable"
      headers:
        Retry-After:
          description: "Retry contacting the endpoint *at least* after seconds.\n\
            See https://tools.ietf.org/html/rfc7231#section-7.1.3"
          format: "int32"
          type: "integer"
      schema:
        $ref: "#/definitions/Problem"
    default:
      description: "Unexpected error"
      schema:
        $ref: "#/definitions/Problem"
  headers:
    Retry-After:
      description: "Retry contacting the endpoint *at least* after seconds.\nSee https://tools.ietf.org/html/rfc7231#section-7.1.3"
      format: "int32"
      type: "integer"
    X-RateLimit-Limit:
      description: "The number of allowed requests in the current period"
      format: "int32"
      type: "integer"
    X-RateLimit-Remaining:
      description: "The number of remaining requests in the current period"
      format: "int32"
      type: "integer"
    X-RateLimit-Reset:
      description: "The number of seconds left in the current period"
      format: "int32"
      type: "integer"
